### Probando el registro de usuarios
POST http://localhost:3000/api/register
Content-Type: application/json

{
   "name": "miguel",
   "email": "mm@gmail.com",
   "password": "salypimienta"
}

### Obteniendo un profile
POST http://localhost:3000/profile/profile 
Content-Type: application/json

{
   "id": "60d4e78e5c674c1d143a0acf"
}

### Eliminando un profile
DELETE http://localhost:3000/profile/deleteprofile
Content-Type: application/json

{
   "id": "60d9fe7a0a9fb244ec8815fa"
}

### Actualizando un Profile
PUT http://localhost:3000/profile/uptadeprofile
Content-Type:  application/json

{   
    "id": "60d4e78e5c674c1d143a0acf",
    "name": "camilo",
    "email": "mariacamilo@gmail.com"
}

### Agregando una pelicula 
POST http://localhost:3000/movies/addmovie
Content-Type: application/json

{
   "title": "joker",
   "runTime": "1h",
   "productionCo": "ggg",
   "director":"walt disney",
   "releaseDate": "1624904420875",
   "genre": "infantil",
   "rating": "7"

}

### Obteniendo las peliculas
GET http://localhost:3000/movies/movies

### Actualizando las peliculas 
PUT http://localhost:3000/movies/uptademovies
Content-Type: application/json

{
    "id": "60da162ad8160a49f0862529",
   "title": "joker",
   "runTime": "3h",
   "productionCo": "ggg",
   "director":"walt disney",
   "releaseDate": "1624904420875",
   "genre": "accion",
   "rating": "7"

}
### Obteniendo una pelicula 
POST http://localhost:3000/movies/movie
Content-Type: application/json

{
    "id": "60da162ad8160a49f0862529"

}

### Eliminando una pelicula 
DELETE http://localhost:3000/movies/deletemovies
Content-Type: application/json

{
    "id": "60da162ad8160a49f0862529"
}

### Buscar pelicula por el titulo
post http://localhost:3000/movies/moviebytitle
Content-Type: application/json

{
    "title": "la sirenita"
}



### Obteniendo todos los comentarios 
GET http://localhost:3000/coments/allcoments

### Agregando todos los comentarios 
POST http://localhost:3000/coments/addcoments
Content-Type: application/json

{
   "content": "ooooooooooooooooooooooooooooooooooooooooooo",
   "author": "miguel",
   "movie": " joker"

}

### Actualizando un comentario
PUT http://localhost:3000/coments/uptadecoments
Content-Type: application/json

{
    "id":"60da20fe3fcd3c1e340f1da8",
   "content": "oo",
   "author": "miguel",
   "movie": " joker"
}

### Eliminando un comentario 
DELETE http://localhost:3000/coments/deletecoments
Content-Type: application/json

{
     "id":"60da20fe3fcd3c1e340f1da8"
}
