### Probando el registro de usuarios
POST http://localhost:3000/api/register
Content-Type: application/json

{
   "name": "miguel",
   "email": "mm@gmail.com",
   "password": "salypimienta"
}

### Probando el login de usuario
POST http://localhost:3000/api/login
Content-Type: application/json

{
   "name": "miguel",
   "email": "mm@gmail.com",
   "password": "salypimienta"
}
### Obteniendo un profile
POST http://localhost:3000/profile/myprofile 
Content-Type: application/json

{
   "id": "60da5cac541c7b5f48cb4be3"
}

### Eliminando un profile
DELETE http://localhost:3000/profile/deleteprofile
Content-Type: application/json

{
   "id": "60d9fe7a0a9fb244ec8815fa"
}

### Actualizando un Profile
PUT http://localhost:3000/profile/uptadeprofile
Content-Type:  application/json

{   
    "id": "60d4e78e5c674c1d143a0acf",
    "name": "camilo",
    "email": "mariacamilo@gmail.com"
}

### Agregando una pelicula 
POST http://localhost:3000/movies/addmovie
Content-Type: application/json

{
   "title": "Inquebrantable",
   "runTime": "120 min",
   "productionCo": "FOX",
   "director":"Salter March",
   "releaseDate": "1624904420873",
   "genre": "Clase B",
   "rating": "10"

}

### Obteniendo las peliculas
GET http://localhost:3000/movies/allmovies

### Actualizando las peliculas 
PUT http://localhost:3000/movies/uptademovies
Content-Type: application/json

{
    "id": "60da162ad8160a49f0862529",
   "title": "joker",
   "runTime": "3h",
   "productionCo": "ggg",
   "director":"walt disney",
   "releaseDate": "1624904420875",
   "genre": "accion",
   "rating": "7"

}
### Obteniendo una pelicula 
POST http://localhost:3000/movies/movie
Content-Type: application/json

{
    "id": "60da15f9d8160a49f0862526"

}

### Eliminando una pelicula 
DELETE http://localhost:3000/movies/deletemovies
Content-Type: application/json

{
    "id": "60da162ad8160a49f0862529"
}

### Buscar pelicula por el titulo
post http://localhost:3000/movies/moviebytitle
Content-Type: application/json

{
    "title": "Inquebrantable"
}



### Obteniendo todos los comentarios 
GET http://localhost:3000/comments/allcomments

### Agregando todos los comentarios 
POST http://localhost:3000/comments/addcomments
Content-Type: application/json

{
   "content": "really good",
   "author": "luis",
   "movie": " la sirenita"

}

### Actualizando un comentario
PUT http://localhost:3000/comments/uptadecomments
Content-Type: application/json

{
   "id":"60db89c8e1642235d0948af7",
   "content": "es muy buena la verdad",
   "author": "jose luis",
   "movie": " maria fernanda"
}

### Eliminando un comentario 
DELETE http://localhost:3000/comments/deletecomments
Content-Type: application/json

{
     "id":"60db89c8e1642235d0948af7"
}
